Feat/show projects
Ascend-Software/ascent-web pull request #17
Opened 2023-10-25 14:29 UTC by MatheusLukas

2023-10-25 14:30 UTC, zKriguer reviewed
Delete those images and commit again.

2023-10-25 14:33 UTC, fellipeutaka requested changes

2023-10-25 14:33 UTC, fellipeutaka commented on src/components/CardsProjects/CardsProjects.tsx
Rename this component to CardsProjects

2023-10-25 18:29 UTC, zKriguer commented on src/components/AttractionButton.tsx
Remove console.log

2023-10-25 18:29 UTC, zKriguer commented on src/components/CalButton.tsx
Remove this console.log too

2023-10-26 13:34 UTC, zKriguer commented on src/components/CardsProjects/CardsProjects.tsx
Updated. Closing this conversation.

2023-10-26 13:35 UTC, fellipeutaka approved these changes

2023-10-26 13:35 UTC, merged